# Generated by Django 5.0.4 on 2024-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
