# Generated by Django 5.0.4 on 2024-06-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
